### ISSUE TITLE
Instagram embed not working

### ISSUE THREAD

**Issue by squareclouds** [sylvainjule/kirby-embed#12]
hello,

i have tested all services and all of them work fine, but instagram is just not working.

the console somehow throws no errors.

![grafik](https://user-images.githubusercontent.com/9073054/196886678-9666f68c-80c8-4bc3-8aa9-17bd76f6615d.png)

I have tried removing some parts of the URL as well but no success.

https://www.instagram.com/p/Cca_3DKLZwz/?utm_source=ig_web_copy_link
(desktop link)

https://www.instagram.com/p/Cca_3DKLZwz
(removed the variables)

https://www.instagram.com/p/Cca_3DKLZwz/?igshid=YmMyMTA2M2Y=
(insta app link)

I am using kirby 3.8.1 (security update) and php 8.0.18 on the live server. on my MAMP twitter didnt work either, but on the live server it does, so not really worth mentioning it.

any help is appreciated! instagram would be an important one for our project :)

**Comment by tristantbg** [comment]
Hi @squareclouds,

Can you check that https://github.com/sylvainjule/kirby-embed/commit/eaa140e62da201f835c7fa8289329e67ef143426 fixes it ?

Thanks

**Comment by squareclouds** [comment]
i can confirm that its working again, but i have to remove all unnecesary information from the url, which might be a bit complicated for non-tech savvy users

this works
https://www.instagram.com/reel/CkQkLziJY1y

this does not (links copied from instagram web and app directly)

https://www.instagram.com/reel/CkQkLziJY1y/?igshid=YmMyMTA2M2Y=
https://www.instagram.com/reel/CkQkLziJY1y/?utm_source=ig_web_copy_link

**Comment by squareclouds** [comment]
follow up to this old issue:

i reccommend you add the script in your code as well, and scrolling="no" to the iframe you add manually since instagram doesnt deliver a 'code' in the response.

`
let iframe = `<iframe src="${value}/embed" width="100%" scrolling="no"></iframe><script async src="//www.instagram.com/embed.js"></script>`
                                iframe = this.htmlToElement(iframe)
                                iframe.setAttribute('referrerpolicy', 'strict-origin-when-cross-origin')

`

**Comment by tristantbg** [comment]
Hi @squareclouds,

I implemented this ! Let me know if it works better.

**Comment by squareclouds** [comment]
@tristantbg thank you! i will try it later!

**Comment by squareclouds** [comment]
@tristantbg it works well! :) but two things:

1) i recommend to remove from the blockquote the attribute

data-instgrm-captioned

since that way the whole caption (which can be quite long) gets removed. your original iframe did the same, it only showed the content, not the caption

2) strangely enough, this also solved the problem from october, i quote

> i can confirm that its working again, but i have to remove all unnecessary information from the url, which might be a bit complicated for non-tech savvy users
> 
> this works
> https://www.instagram.com/reel/CkQkLziJY1y
> 
> this does not (links copied from instagram web and app directly)
> 
> https://www.instagram.com/reel/CkQkLziJY1y/?igshid=YmMyMTA2M2Y=
> https://www.instagram.com/reel/CkQkLziJY1y/?utm_source=ig_web_copy_link

now all the links works!

BUT this link does not (when you remove all all parameters after ? AND dont remove the slash)
https://www.instagram.com/reel/CkQkLziJY1y/ 

in that case the empty blockquote gets loaded, and the field says it synchronized.... which is a wrong feedback :/

![Bildschirm­foto 2023-04-20 um 16 49 17](https://user-images.githubusercontent.com/9073054/233403702-2fa3a4b4-a868-4f1f-aba4-7aeddbc7f2ac.png)

**Comment by tristantbg** [comment]
Hi @squareclouds,

Thank you for testing and for these recommandations.
Will have a look when I have some time.

Best
