### ISSUE TITLE
Consider Bandcamp-support

### ISSUE THREAD

**Issue by tmmmmm** [sylvainjule/kirby-embed#18]
Just raising a hand that there is interest in a Bandcamp-implementation. [oscarotero/Embed](https://github.com/oscarotero/Embed) supports Bandcamp.

**Comment by tristantbg** [comment]
Bandcamp links works with this plugin ;)

**Comment by tmmmmm** [comment]
That's what I tried before opening this issue, but I only get a "Sync failed"-notice and empty/error frontend if I enter valid bandcamp-links for a releases. Same links work in oscarotero's Embed test.
The formatting used: https://{artist}.bandcamp.com/album/{albumtitle}

**Comment by tristantbg** [comment]
That's weird because I just tried with https://barakasound.bandcamp.com/album/baraka and it works.
Do you have the last version ?

**Comment by tmmmmm** [comment]
I installed and updated via Composer, composer.lock says 1.0.8, Kirby is 3.9.5 and vanilla plainkit.

![Screenshot 2023-06-12 at 15 35 55](https://github.com/sylvainjule/kirby-embed/assets/51310587/45bc83af-1aff-4465-a98c-9395baaef418)

**Comment by tmmmmm** [comment]
It seems that nginx is not resolving correctly, at least on my apache-server, it's working. Console logged the same as #3 , so this seems to be the same issue.
