### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [sylvainjule/kirby-embed#20]
Minor UI issue for K4

![screen-capture-1764-Test - Mægazine-plugins test](https://github.com/sylvainjule/kirby-embed/assets/3393422/48f2a5c7-721e-480c-8154-ab72d66c1d79)

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by sylvainjule** [comment]
✓
