### ISSUE TITLE
Sync failed

### ISSUE THREAD

**Issue by plagasul** [sylvainjule/kirby-embed#3]
I am getting a sync failed red message on the field when trying to fetch from the url I provide to it.

Any particular reason this may be happening ?

Thank you

**Comment by sylvainjule** [comment]
I'll need more informations for this.

Local or remote server?
VPS or shared hosting? 
Anything in the console / error message in your Network tab?
Does it fail for all services or only specific ones?

**Comment by plagasul** [comment]
Local server

At least both youtube and vimeo.

This on console:
![image](https://user-images.githubusercontent.com/13966673/79074565-73cb0600-7ced-11ea-8c05-0feffa1c9999.png)

Is this permission related? hmm
Thank you

**Comment by plagasul** [comment]
The plugin folder, as downloaded, is called kirby-embed-master , does that matter?

Thank you

**Comment by sylvainjule** [comment]
No, the issue is with your server config.  As stated in the error message, the class `DOMDocument` is missing. It is used by the library to parse the response. 

Google the message `Class 'DOMDocument' not found` to browse possible fixes.
[Here's one, for example](https://stackoverflow.com/a/47473004)

**Comment by plagasul** [comment]
That solved it, thank you

**Comment by antoine3000** [comment]
Hi,

I also get a `sync failed` error when adding a Soundcloud link.

Here is the message printed in the console:
```
[HTTP/1.1 400 Bad Request 563ms]
Object { status: "error", error: "strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated" }
```

Any idea what to do?
thanks!

**Comment by antoine3000** [comment]
hey! Thanks for the update.
Unfortunately, I still get the error:

```
Object { status: "error", error: "strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated" }
```

**Comment by tmmmmm** [comment]
See #18 / [last post](https://github.com/sylvainjule/kirby-embed/issues/18#issuecomment-1591170662): Same error on nginx, works on Apache.
