### ISSUE TITLE
Twitter won't sync

### ISSUE THREAD

**Issue by nigelewan** [sylvainjule/kirby-embed#4]
URLs for tweets no longer sync. Have tested with multiple types of public tweets using Kirby 3.5.1 and Embed 1.0.1. Other services such as Vimeo and YouTube work as expected.

![Screen Shot 2021-02-05 at 11 51 10](https://user-images.githubusercontent.com/9345906/107063581-8d6f9980-67a8-11eb-83f8-c8b75a829716.png)

**Comment by nigelewan** [comment]
Console gives an error 400.

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/9345906/107065056-54d0bf80-67aa-11eb-9160-23ec0e8bc11e.png">

**Comment by tristantbg** [comment]
Hi @nigelewan,

It works on my end by updating the oEmbed lib.
Quick fix, run :
```
cd plugins/kirby-embed
composer upgrade
```

@sylvainjule : Maybe we can upgrade the packages ?

**Comment by nigelewan** [comment]
Oh man. That was easy. Thanks so much, @tristantbg.
