### ISSUE TITLE
Feature idea: option for a bigger preview

### ISSUE THREAD

**Issue by malvese** [sylvainjule/kirby-embed#8]
**Issue:**
Video previews are quite small, at least for Youtube, because they use the iframe in 'code' which is only 200 pixels wide. Sometimes a bigger preview is more practical to check easily if the correct video is added.

**Suggestion:**
A "cover" option could force a bigger preview size, while keeping the correct aspect ratio for any video.

**My workaround:**
For my needs I was able to achieve this in panel.css, as I only needed a single aspect-ratio:
```
.k-field-name-video_presentation .preview-content {
  padding: 0;
}
.k-field-name-video_presentation .preview-content iframe {
  width: 100%;
  aspect-ratio: 16 / 9;
  height: auto;
}
```
Result with my panel.css:

![image](https://user-images.githubusercontent.com/193492/161378011-b011ca3b-3195-4cac-bc45-6d7c9db633f9.png)

**Comment by tristantbg** [comment]
Good idea.
I have made the changes so it can have a better display for Vimeo and Youtube.
https://github.com/sylvainjule/kirby-embed/commit/29b00faef123a97bb0fd2f0a20b0cd0e125913e2

@sylvainjule can you create a new tag release when you have some time ?

**Comment by tristantbg** [comment]
This release should fix it :
https://github.com/sylvainjule/kirby-embed/releases/tag/1.0.5
